### PR TITLE
增加shadowmask支持

### PR DESCRIPTION
**Pull request by AtheosCode**

### CODE REVIEW

**Comment by Ayfel** [comment]
Oh by the way I also saw you commented out the Baking part of the code, what is the intended workflow in this case? Bake from the lighting tab?

**Comment by AtheosCode** [comment]
Our process is to bake a single scene of the art, and then call this script after the baking result is completed, instead of calling baking through this script, so I commented out the baking code, this code I have in Unity2019.2.2f1 Test, support switching scenarios, support for packed AB

**Comment by Ayfel** [comment]
I am checking and it seems some changes revert back on some edge cases that are undesirable. Like having the same prefab several times will make that lightmap be loaded many times in memory 
image

What I will do is take the new features you incorporated such as shadowmask and incorporate it into the main branch. Also the batching statically breaks a general workflow so I believe is better to leave that out of the functionality of the main project. And if someone want to do it they can manually as you suggest. Let me know what you think, I will be adding those features soon.

**Comment by Ayfel** [comment]
Added shadowmask, thank you a lot! See latest commit

**Pull request closed without merging**
